### ISSUE TITLE
Always recieve a bad request when trying any api on https://staging.itsyou.online/apidocumentation

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#277] opened 2016-10-25 06:18 UTC
https://staging.itsyou.online/apidocumentation
Example:
![400error](https://cloud.githubusercontent.com/assets/15011431/19674920/f581a87e-9a93-11e6-9243-c4f61f6650fb.png)

**Comment by robvanmieghem** [comment] 2016-10-25 07:07
Duplicate of https://github.com/itsyouonline/identityserver/issues/241

**Closed** 2016-10-25 07:07 UTC
Labels: process_duplicate, type_bug
