### ISSUE TITLE
Invited users doesn't get redirected

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#437] opened 2017-02-06 13:51 UTC
Context:  See video from demo of @jdelrue as shared with @LeeSmet 

When a user gets invited via e-mail to access the e-portal, clicks the link, and identifies itself => 2 problems:

1. The invited user ends up on his profile page, instead of getting redirected to the e-portal - normally he would first see an ItsYou.online page where he's supposed to authorize the request, but in this case the authorization was already done before

2. When navigating manually to the e-portal site, the user is requested to login again

**Comment by LeeSmet** [comment] 2017-02-06 15:00
Possible relation to #371

**Comment by LeeSmet** [comment] 2017-02-08 11:03
Additional info: the bug only seems to appear when the user has to go through the verify phonenumber flow on login. This happens when a user has 2 accounts and does 2 factor authentication with SMS. When the account which needs to verify the phone number continues, it gets dropped of at the login page. Also note that no successfull 2FA login seems to be stored, so the user will need to do 2FA again the next time.

**Comment by LeeSmet** [comment] 2017-02-09 11:02
TODO:
- [x] Make sure the user gets redirected
- [x] Save the last 2FA date
- [ ] Fix the url in the sms message to continue the oauth flow and not just confirm the phone number

**Comment by kdeketel** [comment] 2017-02-20 13:50
Request to re-open issue : User registers himself on IYO using the invite link. 

Expected result
After self-registration + clicking Authorize, the new user should be automatically logged in on the webportal.

Actual result
After self-registration + clicking Authorize, the new user lands on the Login page of IYO and has to log in again before he is taken to the webportal.

Issue doesn't seem fixed in the latest release of IYO....

**Comment by LeeSmet** [comment] 2017-02-22 16:49
@kdeketel Could you please specify what invite link you are using and in what context? (Link send out by IYO to invite a user to an organization, Oauth login to authorize your organization to see some of the user information, ...)

**Comment by kdeketel** [comment] 2017-02-23 08:05
Sorry, I can't reproduce anymore.  I did the following test this morning at 8:44:

**invite link:**
http://oostfact-02/security/claimreseller/f55683569bcd182b433e03f70deb9e8a82833e02ef00
**redirect:**
https://itsyou.online/login?client_id=artiliumv2&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http%3A%2F%2Foostfact-02%2Fsecurity%2Fclaimreseller%2Fgo&response_type=code&scope=user%3Aname%2Cuser%3Aemail&state=f55683569bcd182b433e03f70deb9e8a82833e02ef00#/
**Switch to register page**
https://itsyou.online/register?client_id=artiliumv2&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http%3A%2F%2Foostfact-02%2Fsecurity%2Fclaimreseller%2Fgo&response_type=code&scope=user%3Aname%2Cuser%3Aemail&state=f55683569bcd182b433e03f70deb9e8a82833e02ef00#/
**Authorize account:**
https://itsyou.online/#/authorize?client_id=artiliumv2&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http:%2F%2Foostfact-02%2Fsecurity%2Fclaimreseller%2Fgo&response_type=code&scope=user:name,user:email&state=f55683569bcd182b433e03f70deb9e8a82833e02ef00
**Redirect back to portal:**
http://oostfact-02/View/#/authorize?client_id=artiliumv2&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http:%2F%2Foostfact-02%2Fsecurity%2Fclaimreseller%2Fgo&response_type=code&scope=user:name,user:email&state=f55683569bcd182b433e03f70deb9e8a82833e02ef00

It works fine now with new build of the portal, at our end.

Katrien

**Comment by kdeketel** [comment] 2017-02-23 15:52
It would be better though if user could be redirected back to Oostfact portal Login page:

https://itsyou.online/login?client_id=artiliumv2&endpoint=%2Fv1%2Foauth%2Fauthorize&redirect_uri=http%3A%2F%2Foostfact-02%2Fsecurity%2Flogin%2F&response_type=code&scope=user%3Aname%2Cuser%3Aemail&state=7b2860747ed7cf48ab90df91c9b6d67a8a78b0505211#/

**Comment by kdeketel** [comment] 2017-02-23 16:01
or to the portal itself:
http://oostfact-02/View/#/katrienmaster1/dashboard

**Comment by LeeSmet** [comment] 2017-02-23 17:13
Not sure i understand what you mean, after the user authorizes the application on itsyou.online, they should get redirected to the URI you provided?

**Comment by kdeketel** [comment] 2017-02-25 16:25
Hey Lee,

Sorry for the confusion.  The user has to log in twice, as you can see in the enclosed screen recording (WMV)…   If you forward the video to 00:50, you can see where it goes wrong -> the user is prompted to log in a second time after he was already registered and authorized to use the portal.
I’m not sure how this can be solved on a technical level.

Best regards,
Katrien

**Comment by LeeSmet** [comment] 2017-02-27 08:44
Hey Katrien,

I assume you are referring to issue #333. A fix for this issue has been implemented and it will come with the next update for itsyou.online. In short, the user will not be logged out anymore after 2FA, and if the user doesn't have to complete 2FA because he still has a valid authorization and a recent 2FA login, a protected session that can only be used for oauth will be started instead. I hope this will solve your problems.

Sincerely,
Lee

**Comment by kdeketel** [comment] 2017-03-02 07:35
Lee,

OK, yes, let’s wait for issue 333 to get fixed.

Thanks,
Katrien

**Closed** 2017-03-02 10:41 UTC
Labels: state_question, type_bug
