### ISSUE TITLE
address field during signing up to app needs fixing

### ISSUE THREAD

**Issue by bart-at-mobicage** [itsyouonline/identityserver#667] opened 2017-11-15 08:08 UTC
https://docs.greenitglobe.com/ThreeFold/proj_onboarding_tools/issues/118

> 1. 'add address' pops up on top of the screen 
> 2. not clear you need to add more address info (no scroll down or arrow or whatever). 
> 
> Please see video 

![screen shot 2017-11-15 at 09 26 13](https://user-images.githubusercontent.com/17762105/32825988-1363648a-c9e7-11e7-9f62-be161a4b6398.png)

**Comment by LeeSmet** [comment] 2017-11-15 09:41
for 1.: Turns out this is a feature
for 2: This is a duplicate of #659

**Closed by LeeSmet** 2017-11-15 09:41 UTC
