### ISSUE TITLE
GET request does not work for acquiring a JWT

### ISSUE THREAD

**Issue by alichaddad** [itsyouonline/identityserver#503] opened 2017-05-25 14:40 UTC
According to the docs, to acquire a JWT, one should do a GET request like:
`curl -H "Authorization: token OAUTH-TOKEN" https://itsyou.online/v1/oauth/jwt?scope=user:memberof:org1`

This, however, didn't work. Only the POST request did.

```
data = {'aud': 'aliorg', 'scope': 'user:email:main,user:memberof:aliorg'}
headers = {'Authorization': 'token %s' % ouath_token}
url = 'https://itsyou.online/v1/oauth/jwt'
r = requests.get(url, params=data, headers=headers)

print(r.status_code)
Out[59]: 401
```

WIth POST:
```
r = requests.post(url, data=json.dumps(data), headers=headers)
print(r.status_code)
Out[60]: 200
``` 
```

**Comment by LeeSmet** [comment] 2017-05-29 12:05
Tested with curl, ipython, small go program, and in all cases both the GET and the POST request return identical results. Since the issue does not seem to be reproducible, I will close this for now.

**Closed by LeeSmet** 2017-05-29 12:05 UTC
Labels: process_wontfix, type_bug
