### ISSUE TITLE
The api "/users/{username}/info" return empty values

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#278] opened 2016-10-25 09:41 UTC
![userinfo_right](https://cloud.githubusercontent.com/assets/15011431/19680933/2afd2016-9ab0-11e6-97f3-6839b40599ab.png)

![info_error](https://cloud.githubusercontent.com/assets/15011431/19680921/1da226a0-9ab0-11e6-9d00-5966f4b4d98c.png)

**Comment by robvanmieghem** [comment] 2016-10-25 09:46
This is indeed a problem when you have the `user:owner` scope.

**Comment by lucasvanhalst** [comment] 2016-11-28 13:34
This seems to be a duplicate of #246

**Closed by lucasvanhalst** 2016-11-28 13:34 UTC
Labels: type_bug
