### ISSUE TITLE
Organization API - Owner of orgowner organization can't leave the parent organization

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#460] opened 2017-02-16 10:13 UTC
### Scenario
![image](https://cloud.githubusercontent.com/assets/24386820/23016850/b8b9d7c0-f440-11e6-8ee2-68051c69fb88.png)

- **User_1** is owner of **Org-1**.
- **User_2** is owner of **Org-2**.
- **User_1** invited **Org-2** to be **orgowner** of **Org-1**.
- **User_2** accepted the invitation.

### Actual result
When trying to make **User_2** leave **Org-1** , the api response was ```204``` but actually **User_2** still an owner in **Org-1**  and **Org-2** still an **orgowner** Of **Org-1**

**Comment by LeeSmet** [comment] 2017-06-15 12:14
Cannot reproduce, possibly fixed in an earlier version.

After replicating the provided test setup, **user_2** left the **Org-1** organization. Api response was 204, and the **user_2** was no longer explicitly listed in the owner list of **Org-1**. Obviously **User_2** still has ownership rights on **Org-1** as he is a member of **Org-2**, and **Org-2** in turns is an **orgowner** of **Org-1**

**Closed by LeeSmet** 2017-06-15 12:14 UTC
Labels: type_bug
