### ISSUE TITLE
When having only a subset of the requested, memberof scopes, you end up in an endless loop

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#408] opened 2017-01-17 14:15 UTC
This used to work, when requested the scopes `user:memberof:orgA` and `user:memberof:orgB` but you're only member of A, the returned scopes to the external application only contained `user:memberof:orgA`.

**Comment by robvanmieghem** [comment] 2017-01-23 12:19
@iwanbk Just tested this on the current production and this works there. For my test I used the oauth example page in https://github.com/itsyouonline/identityserver/tree/master/docs/examples/go/oauth

requested the `user:memberof:greenitglobe,user:memberof:fake` scope

**Comment by iwanbk** [comment] 2017-01-25 04:34
@robvanmieghem i'm sorry i didn't look this issue carefully.

The issue is not when having only subset of scopes, but when we have both scopes.

My tests:
- 1 scope, member : OK
- 2 scopes, only member of one scope : OK
- 2 scopes, member of both scopes:  endless loop
- 1 scope, not member : OK

**Comment by iwanbk** [comment] 2017-01-25 04:54
```
2 scopes, member of both scopes: endless loop
```
There are another cases using different scopes.
The endless loop happened when i use `user:memberof:labhijau.manager` and `user:memberof:goraml` scopes.

Then i changed the `user:memberof:labhijau.manager` scope to `user:memberof:labhijau`.
It didn't create endless loop, but the JWT token i got contains no scopes.

**Comment by LeeSmet** [comment] 2017-02-06 11:04
Trying to get a JWT from itsYou.Online: 
When asking for 1 memberof scope, if the user can't provide said scope (because he's not member of the organization), the returned JWT will be the string "Unauthorized\n"

**Comment by LeeSmet** [comment] 2017-06-22 09:01
@iwanbk could you verify if this is still valid in the current IYO version?

**Comment by LeeSmet** [comment] 2017-07-25 15:15
This seems to be resolved, closing for now

**Closed by LeeSmet** 2017-07-25 15:15 UTC
Labels: priority_major, type_bug
